@startuml asis_context
!include <C4/C4_Container>

Person_Ext(user, "Пользователь")
Person(enployy, "Сотрудник")

Boundary(e1, "Тёплый дом", "Компания") {
    Boundary(s1, "Управление отоплением", "Domain") {
        Container(c1, "Управление датчиком", "Context")
        Container(c2, "Подключение датчика")
    }
    Boundary(s2, "Мониторинг температуры", "Domain") {
        Container(c3, "Мониторинг температуры")
    }
}
Boundary(e2, "Дом пользователя") {
    System(sensor, "Датчик")
}

Rel(user, c1, "Управляет температурой", "HTTP")
Rel(user, c3, "Мониторит температуру", "HTTP")
Rel(c1, sensor, "Изменяет состояние", "HTTP")
Rel(c3, sensor, "Получает температуру", "HTTP")
Rel(sensor, c2, "Датчик регистрируется", "HTTP")
Rel(enployy, sensor, "Настраивает датчик")

@enduml