@startuml
top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "A user of warmhouse system")
Person(admin, "Admin", "A staff from the company")
System(service, "WarmHouse Service", "Heating and monitoring system")

System_Ext(Sensors, "Temerature sensors", "Measure temperature")
System_Ext(Heating, "Heating system controllers", "Can turn on/off heating")
System_Ext(PaymantService, "Paymant Service", "External paymant service")

Container_Boundary(service, "WarmHouse Service") {
  Container(WebApp, "Web Application", "Browser", "User interface")
  Container(Monolith, "Warm House Service", "Go", "Handles business logic and device interaction")
  ContainerDb(Database, "Database", "PostgreSQL", "Stores users and devices data")
}

Rel(admin, WebApp, "Add new devices to the system")
Rel(user, WebApp, "Request temperature or switch on/off heating")
Rel(WebApp, Monolith, "Make requests to the monolith")
Rel(Monolith, Database, "Write/read data about users and system")
Rel(Monolith, Sensors, "Request temperature")
Rel(Monolith, Heating, "Turn on/off heating")
Rel(Monolith, PaymantService, "Request paymant")

@enduml 